/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btree;

import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Oscar
 */
public class Frame extends javax.swing.JFrame {

    public Frame() {
        this.setLocationRelativeTo(null);
        this.setTitle("Organización de Archivos");
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_insert = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        tf_newKey = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ok_insert = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sp_nums = new javax.swing.JSpinner();
        randomInsertion = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        b_add = new javax.swing.JButton();
        b_del = new javax.swing.JButton();
        d_draw = new javax.swing.JButton();
        d_import = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("Insert new key");

        tf_newKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_newKeyKeyTyped(evt);
            }
        });

        jLabel4.setText("Value");

        ok_insert.setText("Accept");
        ok_insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_insertMouseClicked(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("OR");

        randomInsertion.setText("Random Insertion");
        randomInsertion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                randomInsertionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Dialog_insertLayout = new javax.swing.GroupLayout(Dialog_insert.getContentPane());
        Dialog_insert.getContentPane().setLayout(Dialog_insertLayout);
        Dialog_insertLayout.setHorizontalGroup(
            Dialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_insertLayout.createSequentialGroup()
                .addGroup(Dialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_insertLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(Dialog_insertLayout.createSequentialGroup()
                        .addGroup(Dialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dialog_insertLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel3))
                            .addGroup(Dialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Dialog_insertLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addGroup(Dialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Dialog_insertLayout.createSequentialGroup()
                                            .addComponent(ok_insert)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(Dialog_insertLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tf_newKey, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(Dialog_insertLayout.createSequentialGroup()
                                    .addGap(109, 109, 109)
                                    .addComponent(jLabel5))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_insertLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(randomInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sp_nums, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6))))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Dialog_insertLayout.setVerticalGroup(
            Dialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_insertLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tf_newKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_nums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(randomInsertion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(Dialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_insert)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        jLabel2.setText("B - TREE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 20, 180, 70);

        b_add.setText("Insert");
        b_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_addMouseClicked(evt);
            }
        });
        jPanel1.add(b_add);
        b_add.setBounds(50, 110, 80, 26);

        b_del.setText("Remove");
        b_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_delActionPerformed(evt);
            }
        });
        jPanel1.add(b_del);
        b_del.setBounds(50, 190, 80, 26);

        d_draw.setText("Draw");
        jPanel1.add(d_draw);
        d_draw.setBounds(50, 150, 81, 26);

        d_import.setText("Import from File");
        d_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_importActionPerformed(evt);
            }
        });
        jPanel1.add(d_import);
        d_import.setBounds(50, 230, 130, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btree/bare-tree-clipart1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 60, 210, 243);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Dialog_insert.setVisible(false);
        tf_newKey.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void tf_newKeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_newKeyKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_tf_newKeyKeyTyped

    private void ok_insertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_insertMouseClicked
        
        if(randomInsertion.isSelected()){
            Random r = new Random();
            for(int i = 0; i < (Integer)sp_nums.getValue(); i++){
                int random_value = r.nextInt(100) + 1;
                bTree.insert(random_value);
            }
           JOptionPane.showMessageDialog(this, "Keys added succesfully :D");
        }
        
        else{
            int value = Integer.parseInt(tf_newKey.getText());
            bTree.insert(value);
            JOptionPane.showMessageDialog(this, "Key added succesfully :D");
        }
        
        tf_newKey.setText("");
        randomInsertion.setSelected(false);
        sp_nums.setEnabled(false);
    }//GEN-LAST:event_ok_insertMouseClicked

    private void d_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_importActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_importActionPerformed

    private void b_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_delActionPerformed

    private void b_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_addMouseClicked
        
        sp_nums.setEnabled(false);
        Dialog_insert.pack();
        Dialog_insert.setModal(true);
        Dialog_insert.setLocationRelativeTo(null);
        Dialog_insert.setTitle("Add Key");
        Dialog_insert.setVisible(true);
        
    }//GEN-LAST:event_b_addMouseClicked

    private void randomInsertionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_randomInsertionMouseClicked
       if(randomInsertion.isSelected()){
           sp_nums.setEnabled(true);
       }
       else
           sp_nums.setEnabled(false);
    }//GEN-LAST:event_randomInsertionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_insert;
    private javax.swing.JButton b_add;
    private javax.swing.JButton b_del;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton d_draw;
    private javax.swing.JButton d_import;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton ok_insert;
    private javax.swing.JToggleButton randomInsertion;
    private javax.swing.JSpinner sp_nums;
    private javax.swing.JTextField tf_newKey;
    // End of variables declaration//GEN-END:variables
    Tree bTree = new Tree();
}
